name: hello_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.8

  # Bluetooth libraries
  flutter_blue_plus: ^1.3.4
  flutter_reactive_ble: ^5.3.1

  # Color picker for selecting RGB values
  flutter_colorpicker: ^1.1.0

  # Permission handler for managing permissions like Bluetooth and Location
  permission_handler: ^11.3.1
  flutter_hsvcolor_picker: ^1.5.1
  mailer: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices
  flutter_lints: ^4.0.0

  # Launcher icon generator for setting custom app icons
  flutter_launcher_icons: ^0.9.2

# Flutter icon configuration for both Android and iOS
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Path to your custom app icon

flutter:
  uses-material-design: true

  # Add the path to your asset (icon image)
  assets:
    - assets/icon/
